package dev.nailed.bukkit.scala;

import org.bukkit.plugin.java.JavaPlugin;

import java.lang.reflect.Method;
import java.util.logging.Level;

/**
 * Scala plugin bootstrap class (pure Java).
 * 
 * Auto-generated by bukkit-scala-maven-plugin, users don't need to write this manually.
 */
public abstract class ScalaBootstrap extends JavaPlugin {
    
    private Object scalaPluginInstance = null;
    
    @Override
    public final void onLoad() {
        ScalaRuntime.ensureLoaded(getLogger());
        initScalaPlugin();
        callScalaMethod("onLoad");
    }
    
    @Override
    public final void onEnable() {
        callScalaMethod("onEnable");
    }
    
    @Override
    public final void onDisable() {
        callScalaMethod("onDisable");
    }
    
    /**
     * Subclass must implement this to return the Scala main class name.
     */
    protected abstract String getScalaMainClass();
    
    private void initScalaPlugin() {
        try {
            String className = getScalaMainClass();
            ClassLoader loader = ScalaRuntime.getClassLoader();
            Class<?> scalaClass = loader.loadClass(className);
            
            scalaPluginInstance = scalaClass.getConstructor().newInstance();
            injectPlugin(scalaClass);
            
            getLogger().info("[Scala SDK] Loaded: " + className);
            
        } catch (Exception e) {
            getLogger().log(Level.SEVERE, "[Scala SDK] Failed to load Scala plugin", e);
            throw new RuntimeException(e);
        }
    }
    
    private void injectPlugin(Class<?> scalaClass) {
        // Try setPlugin method
        try {
            Method setPlugin = scalaClass.getMethod("setPlugin", JavaPlugin.class);
            setPlugin.invoke(scalaPluginInstance, this);
            return;
        } catch (NoSuchMethodException ignored) {}
        catch (Exception e) {
            getLogger().warning("[Scala SDK] setPlugin failed: " + e.getMessage());
        }
        
        // Try plugin field
        try {
            java.lang.reflect.Field field = scalaClass.getDeclaredField("plugin");
            field.setAccessible(true);
            field.set(scalaPluginInstance, this);
            return;
        } catch (NoSuchFieldException ignored) {}
        catch (Exception e) {
            getLogger().warning("[Scala SDK] plugin field injection failed: " + e.getMessage());
        }
        
        // Try _plugin field (Scala style)
        try {
            java.lang.reflect.Field field = scalaClass.getDeclaredField("_plugin");
            field.setAccessible(true);
            field.set(scalaPluginInstance, this);
        } catch (NoSuchFieldException ignored) {}
        catch (Exception e) {
            getLogger().warning("[Scala SDK] _plugin field injection failed: " + e.getMessage());
        }
    }
    
    private void callScalaMethod(String methodName) {
        if (scalaPluginInstance == null) return;
        
        try {
            Method method = scalaPluginInstance.getClass().getMethod(methodName);
            method.invoke(scalaPluginInstance);
        } catch (NoSuchMethodException ignored) {
        } catch (Exception e) {
            getLogger().log(Level.SEVERE, "[Scala SDK] " + methodName + " failed", e);
        }
    }
    
    /**
     * Get the Scala plugin instance (for advanced usage).
     */
    public Object getScalaInstance() {
        return scalaPluginInstance;
    }
}
