package dev.nailed.bukkit.scala;

import org.bukkit.plugin.java.JavaPlugin;

import java.io.File;
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.util.logging.Level;

/**
 * Scala plugin bootstrap class (pure Java).
 * 
 * Auto-generated by bukkit-scala-maven-plugin, users don't need to write this manually.
 * Supports Bukkit/Spigot/Paper 1.8-1.21+ with Java 8-21.
 * 
 * Architecture:
 * - ScalaRuntime downloads Scala libraries once
 * - Each plugin gets its own ScalaPluginClassLoader
 * - No ClassLoader injection needed - works on all Java versions without JVM args
 */
public abstract class ScalaBootstrap extends JavaPlugin {
    
    private Object scalaPluginInstance = null;
    private ClassLoader scalaClassLoader = null;
    
    @Override
    public final void onLoad() {
        // Initialize Scala runtime (downloads libs if needed)
        ScalaRuntime.initialize(getLogger());
        
        // Create ClassLoader for this plugin
        File pluginJar = getPluginJarFile();
        scalaClassLoader = ScalaRuntime.createPluginClassLoader(
            pluginJar, 
            getClass().getClassLoader(), 
            getLogger()
        );
        
        initScalaPlugin();
        callScalaMethod("onLoad");
    }
    
    @Override
    public final void onEnable() {
        callScalaMethod("onEnable");
    }
    
    @Override
    public final void onDisable() {
        callScalaMethod("onDisable");
    }
    
    /**
     * Subclass must implement this to return the Scala main class name.
     */
    protected abstract String getScalaMainClass();
    
    /**
     * Get the plugin's JAR file.
     */
    private File getPluginJarFile() {
        try {
            // Method 1: getFile() from JavaPlugin (protected)
            Method getFileMethod = JavaPlugin.class.getDeclaredMethod("getFile");
            getFileMethod.setAccessible(true);
            return (File) getFileMethod.invoke(this);
        } catch (Exception e) {
            // Method 2: Fallback - use CodeSource
            try {
                return new File(getClass().getProtectionDomain().getCodeSource().getLocation().toURI());
            } catch (Exception e2) {
                throw new RuntimeException("[Scala SDK] Cannot determine plugin JAR location", e2);
            }
        }
    }
    
    private void initScalaPlugin() {
        try {
            String className = getScalaMainClass();
            Class<?> scalaClass = scalaClassLoader.loadClass(className);
            
            scalaPluginInstance = scalaClass.getConstructor().newInstance();
            injectPlugin(scalaClass);
            
            getLogger().info("[Scala SDK] Loaded: " + className);
            
        } catch (Exception e) {
            getLogger().log(Level.SEVERE, "[Scala SDK] Failed to load Scala plugin", e);
            throw new RuntimeException(e);
        }
    }
    
    private void injectPlugin(Class<?> scalaClass) {
        // Try Scala 3 setter method: _plugin_$eq(JavaPlugin)
        if (trySetterMethod(scalaClass, "_plugin_$eq", JavaPlugin.class)) return;
        if (trySetterMethod(scalaClass, "dev$nailed$bukkit$scala$BukkitPlugin$_setter_$_plugin_$eq", JavaPlugin.class)) return;
        
        // Try setPlugin method (user-defined)
        if (trySetterMethod(scalaClass, "setPlugin", JavaPlugin.class)) return;
        
        // Try field injection (multiple naming conventions)
        if (tryFieldInjection(scalaClass, "_plugin")) return;
        if (tryFieldInjection(scalaClass, "plugin")) return;
        if (tryFieldInjection(scalaClass, "dev$nailed$bukkit$scala$BukkitPlugin$$_plugin")) return;
        
        // Search all fields for JavaPlugin type
        if (tryFindPluginField(scalaClass)) return;
        
        getLogger().warning("[Scala SDK] Could not inject plugin reference - some features may not work");
    }
    
    private boolean trySetterMethod(Class<?> clazz, String methodName, Class<?> paramType) {
        try {
            Method method = clazz.getMethod(methodName, paramType);
            method.invoke(scalaPluginInstance, this);
            getLogger().fine("[Scala SDK] Injected via " + methodName + "()");
            return true;
        } catch (NoSuchMethodException ignored) {
            return false;
        } catch (Exception e) {
            getLogger().fine("[Scala SDK] " + methodName + " failed: " + e.getMessage());
            return false;
        }
    }
    
    private boolean tryFieldInjection(Class<?> clazz, String fieldName) {
        // Search in class hierarchy
        Class<?> current = clazz;
        while (current != null && current != Object.class) {
            try {
                Field field = current.getDeclaredField(fieldName);
                field.setAccessible(true);
                field.set(scalaPluginInstance, this);
                getLogger().fine("[Scala SDK] Injected via field: " + fieldName);
                return true;
            } catch (NoSuchFieldException ignored) {
                current = current.getSuperclass();
            } catch (Exception e) {
                getLogger().fine("[Scala SDK] Field " + fieldName + " injection failed: " + e.getMessage());
                return false;
            }
        }
        return false;
    }
    
    private boolean tryFindPluginField(Class<?> clazz) {
        // Search all fields for JavaPlugin type
        Class<?> current = clazz;
        while (current != null && current != Object.class) {
            for (Field field : current.getDeclaredFields()) {
                if (JavaPlugin.class.isAssignableFrom(field.getType())) {
                    try {
                        field.setAccessible(true);
                        field.set(scalaPluginInstance, this);
                        getLogger().fine("[Scala SDK] Injected via discovered field: " + field.getName());
                        return true;
                    } catch (Exception e) {
                        getLogger().fine("[Scala SDK] Field " + field.getName() + " injection failed: " + e.getMessage());
                    }
                }
            }
            current = current.getSuperclass();
        }
        return false;
    }
    
    private void callScalaMethod(String methodName) {
        if (scalaPluginInstance == null) return;
        
        // Set context classloader to ensure Scala classes can be found
        ClassLoader originalCL = Thread.currentThread().getContextClassLoader();
        try {
            Thread.currentThread().setContextClassLoader(scalaClassLoader);
            Method method = scalaPluginInstance.getClass().getMethod(methodName);
            method.invoke(scalaPluginInstance);
        } catch (NoSuchMethodException ignored) {
        } catch (Exception e) {
            getLogger().log(Level.SEVERE, "[Scala SDK] " + methodName + " failed", e);
        } finally {
            Thread.currentThread().setContextClassLoader(originalCL);
        }
    }
    
    /**
     * Get the Scala ClassLoader for this plugin.
     */
    public ClassLoader getScalaClassLoader() {
        return scalaClassLoader;
    }
    
    /**
     * Get the Scala plugin instance (for advanced usage).
     */
    public Object getScalaInstance() {
        return scalaPluginInstance;
    }
}
