name: ScalaExamplePlugin
version: 1.0.0
main: com.example.ExamplePlugin
api-version: 1.16
description: Example Scala 3 Bukkit plugin demonstrating Scala-specific features
author: nailed.dev

commands:
  scala:
    description: Scala 3 demo command
    usage: /scala [info|coins <n>|rank <name>]
